# Site settings
title: monome
email: help@monome.org
baseurl: /docs/ # the subpath of your site, e.g. /blog/

# Build settings
permalink: pretty
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: lua
    css_class: 'highlight'

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
